### ISSUE TITLE
Client - create header component

### ISSUE THREAD

**Issue by uuidforme** [happy-hour-app/happy-hour-app#16]
make title banner
make city banner
make date banner
import props for date and location from Main App

**Comment by jelani504** [comment]
![Screen Shot 2018-06-03 at 2.09.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0f1f5d314fc500130fda27/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f06b7191a37af112224f5e565ecc3c4a4356bcbbd671f3e57862804e0ebfd06d5e73923c12f9b1d717bc01ba22831983e5e88f1ed2f42f67b6d5db1063474f4dcbed5727a29941c95df443e14856a7113665e3702431.png)
![Screen Shot 2018-06-03 at 2.15.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b0f1f5d314fc500130fda27/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f06b7191a37af1132e4f5c5a5ecc3c4a4356bcbbd671f3e57862804e0ebfd06d5e73923c12f9b1d717bc01ba22831983e5e88f1ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df443e14856a0133e60ee7f2431.png)
